name: simple_fsm
description: "An easy to use finite state machine implementation using enums for states and events."
version: 0.1.0
repository: https://github.com/SongbookPro/dart_fsm

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
