name: simple_fsm
description: "An easy to use finite state machine implementation using enums for states and events."
version: 0.2.0+2
repository: https://github.com/SongbookPro/dart_fsm

environment:
  sdk: ^3.0.0

dependencies:
  logging: ^1.0.0

dev_dependencies:
  test: ^1.25.0
  lints: ^4.0.0

flutter:
